const { defineProps, defineSlots, defineEmits, defineExpose, defineModel, defineOptions, withDefaults, } = await import('vue');
; /* PartiallyEnd: #3632/scriptSetup.vue */
const __VLS_fnComponent = (await import('vue')).defineComponent({});
;
let __VLS_functionalComponentProps;
function __VLS_template() {
    const __VLS_ctx = {};
    const __VLS_localComponents = {
        ...{},
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_components;
    const __VLS_localDirectives = {
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_directives;
    let __VLS_styleScopedClasses;
    // CSS variable injection 
    // CSS variable injection end 
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.section, __VLS_intrinsicElements.section)({ ...{ class: ("w-full bg-[#3A6148] py-20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("max-w-[1702px] mx-auto px-6 md:px-[69px]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("mb-8 w-full rounded-3xl relative overflow-visible") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("absolute inset-0 bg-white/10 backdrop-blur-md hover:bg-white/20 transition-all duration-300 rounded-3xl") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col md:flex-row h-full relative") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("w-full h-[386px] md:w-[45%] p-8 md:p-12 flex flex-col items-center justify-center z-10 relative ") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-3xl md:text-4xl font-bold text-white mb-2 text-center") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.br, __VLS_intrinsicElements.br)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("text-[#FFB800] inline-block mt-1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ class: ("bg-[#FFB800] text-white px-6 py-2 md:px-8 md:py-3 rounded-full mt-6 hover:bg-opacity-90 transition-all duration-300") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("absolute top-[-60px] right-[-20px] md:block hidden z-20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ src: ("../assets/images/image6.png"), alt: ("Person using phone"), ...{ class: ("w-[980px] h-auto object-cover transform translate-y-[-418px]  translate-x-20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("grid grid-cols-1 md:grid-cols-2 gap-8 mb-8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rounded-3xl overflow-hidden group relative") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("absolute inset-0 bg-white/10 backdrop-blur-md group-hover:bg-white/20 transition-all duration-300") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative z-10 p-6 md:p-8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-xl md:text-2xl font-bold text-white mb-4 md:mb-6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("text-[#FFB800]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ src: ("../assets/images/image.svg"), alt: ("Trading Interface"), ...{ class: ("w-full rounded-lg") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rounded-3xl overflow-hidden group relative") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("absolute inset-0 bg-white/10 backdrop-blur-md group-hover:bg-white/20 transition-all duration-300") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative z-10 p-6 md:p-8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-xl md:text-2xl font-bold text-white mb-4 md:mb-6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.br)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ src: ("../assets/images/image8.svg"), alt: ("X2 3D Text"), ...{ class: ("w-full rounded-lg") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("mb-8 w-full rounded-3xl overflow-hidden group relative") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("absolute inset-0 bg-white/10 backdrop-blur-md group-hover:bg-white/20 transition-all duration-300") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative z-10 p-6 md:p-12") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("flex flex-col md:flex-row justify-between items-center") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("mb-6 md:mb-0") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h2, __VLS_intrinsicElements.h2)({ ...{ class: ("text-3xl md:text-4xl font-bold") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("text-[#FFB800]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("text-white") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.p, __VLS_intrinsicElements.p)({ ...{ class: ("text-xl md:text-2xl text-white") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ class: ("bg-[#FFB800] text-white px-6 py-2 md:px-8 md:py-3 rounded-full mt-4 md:mt-6 hover:bg-opacity-90 transition-all duration-300") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("w-full md:w-1/2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ src: ("../assets/images/Untitled-1.svg"), alt: ("Client Image"), ...{ class: ("w-full h-auto rounded-lg object-cover") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("grid grid-cols-1 md:grid-cols-2 gap-8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rounded-3xl overflow-hidden group relative") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("absolute inset-0 bg-white/10 backdrop-blur-md group-hover:bg-white/20 transition-all duration-300") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative z-10 p-6 md:p-8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-xl md:text-2xl font-bold text-white mb-4 md:mb-6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.br)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative h-48") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("absolute top-0 left-0 bg-green-500 text-white text-xs md:text-sm px-2 py-1 md:px-3 md:py-1 rounded") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("absolute bottom-0 left-0 bg-red-500 text-white text-xs md:text-sm px-2 py-1 md:px-3 md:py-1 rounded") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.svg, __VLS_intrinsicElements.svg)({ ...{ class: ("w-full h-full") }, viewBox: ("0 0 400 200"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.path)({ d: ("M0,100 C100,80 200,120 400,60"), stroke: ("#22C55E"), "stroke-width": ("3"), fill: ("none"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rounded-3xl overflow-hidden group relative") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("absolute inset-0 bg-white/10 backdrop-blur-md group-hover:bg-white/20 transition-all duration-300") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("relative z-10 p-6 md:p-8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.h3, __VLS_intrinsicElements.h3)({ ...{ class: ("text-xl md:text-2xl font-bold mb-4 md:mb-6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("text-[#FFB800]") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("text-white") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.br)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.span, __VLS_intrinsicElements.span)({ ...{ class: ("text-white") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ src: ("../assets/images/image14.svg"), alt: ("Golden 5"), ...{ class: ("w-36 h-36 md:w-48 md:h-48 mx-auto") }, });
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['bg-[#3A6148]'];
    __VLS_styleScopedClasses['py-20'];
    __VLS_styleScopedClasses['max-w-[1702px]'];
    __VLS_styleScopedClasses['mx-auto'];
    __VLS_styleScopedClasses['px-6'];
    __VLS_styleScopedClasses['md:px-[69px]'];
    __VLS_styleScopedClasses['mb-8'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['rounded-3xl'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['overflow-visible'];
    __VLS_styleScopedClasses['absolute'];
    __VLS_styleScopedClasses['inset-0'];
    __VLS_styleScopedClasses['bg-white/10'];
    __VLS_styleScopedClasses['backdrop-blur-md'];
    __VLS_styleScopedClasses['hover:bg-white/20'];
    __VLS_styleScopedClasses['transition-all'];
    __VLS_styleScopedClasses['duration-300'];
    __VLS_styleScopedClasses['rounded-3xl'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['md:flex-row'];
    __VLS_styleScopedClasses['h-full'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['h-[386px]'];
    __VLS_styleScopedClasses['md:w-[45%]'];
    __VLS_styleScopedClasses['p-8'];
    __VLS_styleScopedClasses['md:p-12'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['items-center'];
    __VLS_styleScopedClasses['justify-center'];
    __VLS_styleScopedClasses['z-10'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['text-3xl'];
    __VLS_styleScopedClasses['md:text-4xl'];
    __VLS_styleScopedClasses['font-bold'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['mb-2'];
    __VLS_styleScopedClasses['text-center'];
    __VLS_styleScopedClasses['text-[#FFB800]'];
    __VLS_styleScopedClasses['inline-block'];
    __VLS_styleScopedClasses['mt-1'];
    __VLS_styleScopedClasses['bg-[#FFB800]'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['px-6'];
    __VLS_styleScopedClasses['py-2'];
    __VLS_styleScopedClasses['md:px-8'];
    __VLS_styleScopedClasses['md:py-3'];
    __VLS_styleScopedClasses['rounded-full'];
    __VLS_styleScopedClasses['mt-6'];
    __VLS_styleScopedClasses['hover:bg-opacity-90'];
    __VLS_styleScopedClasses['transition-all'];
    __VLS_styleScopedClasses['duration-300'];
    __VLS_styleScopedClasses['absolute'];
    __VLS_styleScopedClasses['top-[-60px]'];
    __VLS_styleScopedClasses['right-[-20px]'];
    __VLS_styleScopedClasses['md:block'];
    __VLS_styleScopedClasses['hidden'];
    __VLS_styleScopedClasses['z-20'];
    __VLS_styleScopedClasses['w-[980px]'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['object-cover'];
    __VLS_styleScopedClasses['transform'];
    __VLS_styleScopedClasses['translate-y-[-418px]'];
    __VLS_styleScopedClasses['translate-x-20'];
    __VLS_styleScopedClasses['grid'];
    __VLS_styleScopedClasses['grid-cols-1'];
    __VLS_styleScopedClasses['md:grid-cols-2'];
    __VLS_styleScopedClasses['gap-8'];
    __VLS_styleScopedClasses['mb-8'];
    __VLS_styleScopedClasses['rounded-3xl'];
    __VLS_styleScopedClasses['overflow-hidden'];
    __VLS_styleScopedClasses['group'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['absolute'];
    __VLS_styleScopedClasses['inset-0'];
    __VLS_styleScopedClasses['bg-white/10'];
    __VLS_styleScopedClasses['backdrop-blur-md'];
    __VLS_styleScopedClasses['group-hover:bg-white/20'];
    __VLS_styleScopedClasses['transition-all'];
    __VLS_styleScopedClasses['duration-300'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['z-10'];
    __VLS_styleScopedClasses['p-6'];
    __VLS_styleScopedClasses['md:p-8'];
    __VLS_styleScopedClasses['text-xl'];
    __VLS_styleScopedClasses['md:text-2xl'];
    __VLS_styleScopedClasses['font-bold'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['mb-4'];
    __VLS_styleScopedClasses['md:mb-6'];
    __VLS_styleScopedClasses['text-[#FFB800]'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['rounded-lg'];
    __VLS_styleScopedClasses['rounded-3xl'];
    __VLS_styleScopedClasses['overflow-hidden'];
    __VLS_styleScopedClasses['group'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['absolute'];
    __VLS_styleScopedClasses['inset-0'];
    __VLS_styleScopedClasses['bg-white/10'];
    __VLS_styleScopedClasses['backdrop-blur-md'];
    __VLS_styleScopedClasses['group-hover:bg-white/20'];
    __VLS_styleScopedClasses['transition-all'];
    __VLS_styleScopedClasses['duration-300'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['z-10'];
    __VLS_styleScopedClasses['p-6'];
    __VLS_styleScopedClasses['md:p-8'];
    __VLS_styleScopedClasses['text-xl'];
    __VLS_styleScopedClasses['md:text-2xl'];
    __VLS_styleScopedClasses['font-bold'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['mb-4'];
    __VLS_styleScopedClasses['md:mb-6'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['rounded-lg'];
    __VLS_styleScopedClasses['mb-8'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['rounded-3xl'];
    __VLS_styleScopedClasses['overflow-hidden'];
    __VLS_styleScopedClasses['group'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['absolute'];
    __VLS_styleScopedClasses['inset-0'];
    __VLS_styleScopedClasses['bg-white/10'];
    __VLS_styleScopedClasses['backdrop-blur-md'];
    __VLS_styleScopedClasses['group-hover:bg-white/20'];
    __VLS_styleScopedClasses['transition-all'];
    __VLS_styleScopedClasses['duration-300'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['z-10'];
    __VLS_styleScopedClasses['p-6'];
    __VLS_styleScopedClasses['md:p-12'];
    __VLS_styleScopedClasses['flex'];
    __VLS_styleScopedClasses['flex-col'];
    __VLS_styleScopedClasses['md:flex-row'];
    __VLS_styleScopedClasses['justify-between'];
    __VLS_styleScopedClasses['items-center'];
    __VLS_styleScopedClasses['mb-6'];
    __VLS_styleScopedClasses['md:mb-0'];
    __VLS_styleScopedClasses['text-3xl'];
    __VLS_styleScopedClasses['md:text-4xl'];
    __VLS_styleScopedClasses['font-bold'];
    __VLS_styleScopedClasses['text-[#FFB800]'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['text-xl'];
    __VLS_styleScopedClasses['md:text-2xl'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['bg-[#FFB800]'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['px-6'];
    __VLS_styleScopedClasses['py-2'];
    __VLS_styleScopedClasses['md:px-8'];
    __VLS_styleScopedClasses['md:py-3'];
    __VLS_styleScopedClasses['rounded-full'];
    __VLS_styleScopedClasses['mt-4'];
    __VLS_styleScopedClasses['md:mt-6'];
    __VLS_styleScopedClasses['hover:bg-opacity-90'];
    __VLS_styleScopedClasses['transition-all'];
    __VLS_styleScopedClasses['duration-300'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['md:w-1/2'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['h-auto'];
    __VLS_styleScopedClasses['rounded-lg'];
    __VLS_styleScopedClasses['object-cover'];
    __VLS_styleScopedClasses['grid'];
    __VLS_styleScopedClasses['grid-cols-1'];
    __VLS_styleScopedClasses['md:grid-cols-2'];
    __VLS_styleScopedClasses['gap-8'];
    __VLS_styleScopedClasses['rounded-3xl'];
    __VLS_styleScopedClasses['overflow-hidden'];
    __VLS_styleScopedClasses['group'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['absolute'];
    __VLS_styleScopedClasses['inset-0'];
    __VLS_styleScopedClasses['bg-white/10'];
    __VLS_styleScopedClasses['backdrop-blur-md'];
    __VLS_styleScopedClasses['group-hover:bg-white/20'];
    __VLS_styleScopedClasses['transition-all'];
    __VLS_styleScopedClasses['duration-300'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['z-10'];
    __VLS_styleScopedClasses['p-6'];
    __VLS_styleScopedClasses['md:p-8'];
    __VLS_styleScopedClasses['text-xl'];
    __VLS_styleScopedClasses['md:text-2xl'];
    __VLS_styleScopedClasses['font-bold'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['mb-4'];
    __VLS_styleScopedClasses['md:mb-6'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['h-48'];
    __VLS_styleScopedClasses['absolute'];
    __VLS_styleScopedClasses['top-0'];
    __VLS_styleScopedClasses['left-0'];
    __VLS_styleScopedClasses['bg-green-500'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['text-xs'];
    __VLS_styleScopedClasses['md:text-sm'];
    __VLS_styleScopedClasses['px-2'];
    __VLS_styleScopedClasses['py-1'];
    __VLS_styleScopedClasses['md:px-3'];
    __VLS_styleScopedClasses['md:py-1'];
    __VLS_styleScopedClasses['rounded'];
    __VLS_styleScopedClasses['absolute'];
    __VLS_styleScopedClasses['bottom-0'];
    __VLS_styleScopedClasses['left-0'];
    __VLS_styleScopedClasses['bg-red-500'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['text-xs'];
    __VLS_styleScopedClasses['md:text-sm'];
    __VLS_styleScopedClasses['px-2'];
    __VLS_styleScopedClasses['py-1'];
    __VLS_styleScopedClasses['md:px-3'];
    __VLS_styleScopedClasses['md:py-1'];
    __VLS_styleScopedClasses['rounded'];
    __VLS_styleScopedClasses['w-full'];
    __VLS_styleScopedClasses['h-full'];
    __VLS_styleScopedClasses['rounded-3xl'];
    __VLS_styleScopedClasses['overflow-hidden'];
    __VLS_styleScopedClasses['group'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['absolute'];
    __VLS_styleScopedClasses['inset-0'];
    __VLS_styleScopedClasses['bg-white/10'];
    __VLS_styleScopedClasses['backdrop-blur-md'];
    __VLS_styleScopedClasses['group-hover:bg-white/20'];
    __VLS_styleScopedClasses['transition-all'];
    __VLS_styleScopedClasses['duration-300'];
    __VLS_styleScopedClasses['relative'];
    __VLS_styleScopedClasses['z-10'];
    __VLS_styleScopedClasses['p-6'];
    __VLS_styleScopedClasses['md:p-8'];
    __VLS_styleScopedClasses['text-xl'];
    __VLS_styleScopedClasses['md:text-2xl'];
    __VLS_styleScopedClasses['font-bold'];
    __VLS_styleScopedClasses['mb-4'];
    __VLS_styleScopedClasses['md:mb-6'];
    __VLS_styleScopedClasses['text-[#FFB800]'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['text-white'];
    __VLS_styleScopedClasses['w-36'];
    __VLS_styleScopedClasses['h-36'];
    __VLS_styleScopedClasses['md:w-48'];
    __VLS_styleScopedClasses['md:h-48'];
    __VLS_styleScopedClasses['mx-auto'];
    var __VLS_slots;
    var __VLS_inheritedAttrs;
    const __VLS_refs = {};
    var $refs;
    var $el;
    return {
        attrs: {},
        slots: __VLS_slots,
        refs: $refs,
        rootEl: $el,
    };
}
;
const __VLS_self = (await import('vue')).defineComponent({
    setup() {
        return {};
    },
});
export default (await import('vue')).defineComponent({
    setup() {
        return {};
    },
    __typeEl: {},
});
; /* PartiallyEnd: #4569/main.vue */
